/**
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities.validation;

import inf.thm.de.entities.validation.AbstractEntitiesValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class EntitiesValidator extends AbstractEntitiesValidator {
}
