/*
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
