/*
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EntitiesStandaloneSetup extends EntitiesStandaloneSetupGenerated {

	def static void doSetup() {
		new EntitiesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
