/*
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEntitiesScopeProvider extends DelegatingScopeProvider {
}
