/**
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities.ui.contentassist;

import inf.thm.de.entities.ui.contentassist.AbstractEntitiesProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class EntitiesProposalProvider extends AbstractEntitiesProposalProvider {
}
