/*
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities.ui.tests;

import com.google.inject.Injector;
import inf.thm.de.entities.ui.internal.EntitiesActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EntitiesUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EntitiesActivator.getInstance().getInjector("inf.thm.de.entities.Entities");
	}

}
