/**
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities;

import inf.thm.de.entities.AbstractEntitiesRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntitiesRuntimeModule extends AbstractEntitiesRuntimeModule {
}
