/**
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities.ui;

import inf.thm.de.entities.ui.AbstractEntitiesUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class EntitiesUiModule extends AbstractEntitiesUiModule {
  public EntitiesUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
