/**
 * generated by Xtext 2.18.0
 */
package inf.thm.de.entities.ide;

import inf.thm.de.entities.ide.AbstractEntitiesIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class EntitiesIdeModule extends AbstractEntitiesIdeModule {
}
